import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()

GMAIL_USER = os.getenv("GMAIL_USER")
GMAIL_PASSWORD = os.getenv("GMAIL_PASSWORD")
RECIPIENT_EMAIL = os.getenv("RECIPIENT_EMAIL")


def send_weather_brief_email(subject: str, brief: str) -> bool:
    """
    Sends the weather brief via Gmail with a custom subject line.
    Args:
        subject: Email subject line (generated by LLM)
        brief: Weather brief text (generated by LLM)
    Returns True if successful, False otherwise.
    """
    
    try:
        # Create message
        message = MIMEMultipart("alternative")
        message["Subject"] = subject
        message["From"] = GMAIL_USER
        message["To"] = RECIPIENT_EMAIL
        
        # Create HTML version
        html = f"""\
        <html>
          <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
              <h2 style="color: #2c3e50;">{subject}</h2>
              <p style="font-size: 16px; margin: 20px 0;">
                {brief}
              </p>
              <hr style="border: none; border-top: 1px solid #ddd; margin: 30px 0;">
              <p style="font-size: 12px; color: #7f8c8d;">
                This brief was generated automatically at {__import__('datetime').datetime.now().strftime('%H:%M')} CET
              </p>
            </div>
          </body>
        </html>
        """
        
        part = MIMEText(html, "html")
        message.attach(part)
        
        # Send email via Gmail SMTP
        server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login(GMAIL_USER, GMAIL_PASSWORD)
        server.sendmail(GMAIL_USER, RECIPIENT_EMAIL, message.as_string())
        server.quit()
        
        print(f"✅ Email sent successfully to {RECIPIENT_EMAIL}")
        print(f"   Subject: {subject}")
        return True
    
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False